foreground #cccccc
background #000000
cursor none
selection_foreground none
selection_background none

# normal
color0 #111111
color1 #ee4549
color2 #59b259
color3 #c86131
color4 #3773af
color5 #b259b2
color6 #37afaf
color7 #cccccc

# bright
color8 #888888
color9 #f2777a
color10 #99cc99
color11 #ffcc66
color12 #6699cc
color13 #cc99cc
color14 #66cccc
color15 #f2f0ec
