-- Palette: ~/dev/terminal-themes/themes/eighties-black.yaml
-- SPDX-License-Identifier: MIT
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "eighties-black"

local p = {
  bg = "#000000",
  fg = "#cccccc",
  cursor = "#cccccc",
  black = "#111111",
  red = "#ee4549",
  green = "#59b259",
  yellow = "#c86131",
  blue = "#3773af",
  magenta = "#b259b2",
  cyan = "#37afaf",
  white = "#cccccc",
  bright_black = "#888888",
  bright_red = "#f2777a",
  bright_green = "#99cc99",
  bright_yellow = "#ffcc66",
  bright_blue = "#6699cc",
  bright_magenta = "#cc99cc",
  bright_cyan = "#66cccc",
  bright_white = "#f2f0ec",
  -- same family; peach is Kempson eighties orange
  peach = "#f99157",
  teal = "#6bb8b8",
  dim_yellow = "#c4a35a",
  hot_pink = "#ff5faf",
  ice = "#5fd7ff",
}

local function hl(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

-- UI
hl("Normal", { fg = p.fg, bg = p.bg })
hl("NormalNC", { fg = p.fg, bg = p.bg })
hl("NormalFloat", { fg = p.fg, bg = p.black })
hl("FloatBorder", { fg = p.bright_black, bg = p.black })
hl("FloatTitle", { fg = p.bright_yellow, bg = p.black, bold = true })
hl("WinSeparator", { fg = p.black, bg = p.bg })
hl("VertSplit", { fg = p.black, bg = p.bg })
hl("LineNr", { fg = p.bright_black, bg = p.bg })
hl("LineNrAbove", { fg = p.bright_black, bg = p.bg })
hl("LineNrBelow", { fg = p.bright_black, bg = p.bg })
hl("Cursor", { fg = p.bg, bg = p.cursor })
hl("lCursor", { fg = p.bg, bg = p.cursor })
hl("CursorLine", { bg = p.black })
hl("CursorColumn", { bg = p.black })
hl("CursorLineNr", { fg = p.bright_yellow, bg = p.black, bold = true })
hl("CursorLineSign", { bg = p.black })
hl("CursorLineFold", { fg = p.bright_black, bg = p.black })
hl("SignColumn", { fg = p.bright_black, bg = p.bg })
hl("FoldColumn", { fg = p.bright_black, bg = p.bg })
hl("Folded", { fg = p.bright_black, bg = p.black })
hl("ColorColumn", { bg = p.black })
hl("Visual", { fg = p.bg, bg = p.fg })
hl("VisualNOS", { fg = p.bg, bg = p.fg })
hl("Search", { fg = p.bg, bg = p.bright_yellow })
hl("IncSearch", { fg = p.bg, bg = p.yellow })
hl("CurSearch", { fg = p.bg, bg = p.yellow })
hl("Substitute", { fg = p.bg, bg = p.bright_red })
hl("MatchParen", { fg = p.bright_cyan, bold = true })
hl("Whitespace", { fg = p.black })
hl("NonText", { fg = p.black })
hl("EndOfBuffer", { fg = p.bg })
hl("SpecialKey", { fg = p.black })
hl("Directory", { fg = p.bright_blue })
hl("Title", { fg = p.bright_yellow, bold = true })
hl("Question", { fg = p.bright_green })
hl("MoreMsg", { fg = p.bright_green })
hl("ModeMsg", { fg = p.fg, bold = true })
hl("ErrorMsg", { fg = p.bright_red, bold = true })
hl("WarningMsg", { fg = p.bright_yellow })
hl("MsgArea", { fg = p.fg, bg = p.bg })
hl("WildMenu", { fg = p.bg, bg = p.bright_yellow, bold = true })
hl("Pmenu", { fg = p.fg, bg = p.black })
hl("PmenuSel", { fg = p.bg, bg = p.bright_blue })
hl("PmenuSbar", { bg = p.black })
hl("PmenuThumb", { bg = p.bright_black })
hl("PmenuKind", { fg = p.bright_magenta, bg = p.black })
hl("PmenuKindSel", { fg = p.bg, bg = p.bright_blue })
hl("PmenuExtra", { fg = p.bright_black, bg = p.black })
hl("PmenuExtraSel", { fg = p.bg, bg = p.bright_blue })
hl("StatusLine", { fg = p.fg, bg = p.black })
hl("StatusLineNC", { fg = p.bright_black, bg = p.black })
hl("TabLine", { fg = p.bright_black, bg = p.black })
hl("TabLineFill", { bg = p.bg })
hl("TabLineSel", { fg = p.fg, bg = p.bg, bold = true })
hl("WinBar", { fg = p.bright_black, bg = p.bg })
hl("WinBarNC", { fg = p.bright_black, bg = p.bg })
hl("QuickFixLine", { bg = p.black })
hl("SpellBad", { sp = p.bright_red, undercurl = true })
hl("SpellCap", { sp = p.bright_blue, undercurl = true })
hl("SpellLocal", { sp = p.bright_cyan, undercurl = true })
hl("SpellRare", { sp = p.bright_magenta, undercurl = true })
hl("Conceal", { fg = p.bright_black })

-- Syntax: brights for the eighties accents; normal yellow is the orange
hl("Comment", { fg = p.bright_black, italic = true })
hl("Constant", { fg = p.yellow })
hl("String", { fg = p.bright_green })
hl("Character", { fg = p.bright_green })
hl("Number", { fg = p.yellow })
hl("Boolean", { fg = p.yellow })
hl("Float", { fg = p.yellow })
hl("Identifier", { fg = p.bright_red })
hl("Function", { fg = p.bright_blue })
hl("Statement", { fg = p.bright_magenta })
hl("Conditional", { fg = p.bright_magenta })
hl("Repeat", { fg = p.bright_magenta })
hl("Label", { fg = p.bright_magenta })
hl("Operator", { fg = p.bright_cyan })
hl("Keyword", { fg = p.bright_magenta })
hl("Exception", { fg = p.bright_red })
hl("PreProc", { fg = p.bright_yellow })
hl("Include", { fg = p.bright_blue })
hl("Define", { fg = p.bright_magenta })
hl("Macro", { fg = p.bright_red })
hl("PreCondit", { fg = p.bright_yellow })
hl("Type", { fg = p.bright_yellow })
hl("StorageClass", { fg = p.bright_yellow })
hl("Structure", { fg = p.bright_yellow })
hl("Typedef", { fg = p.bright_yellow })
hl("Special", { fg = p.bright_cyan })
hl("SpecialChar", { fg = p.yellow })
hl("Tag", { fg = p.bright_red })
hl("Delimiter", { fg = p.bright_black })
hl("SpecialComment", { fg = p.bright_black, italic = true })
hl("Debug", { fg = p.bright_red })
hl("Underlined", { fg = p.bright_blue, underline = true })
hl("Ignore", { fg = p.bright_black })
hl("Error", { fg = p.bright_red })
hl("Todo", { fg = p.bright_yellow, bold = true })
hl("Added", { fg = p.bright_green })
hl("Changed", { fg = p.bright_yellow })
hl("Removed", { fg = p.bright_red })

hl("DiffAdd", { fg = p.bright_green, bg = p.black })
hl("DiffChange", { fg = p.bright_yellow, bg = p.black })
hl("DiffDelete", { fg = p.bright_red, bg = p.black })
hl("DiffText", { fg = p.bright_yellow, bg = p.black, bold = true })

hl("DiagnosticError", { fg = p.bright_red })
hl("DiagnosticWarn", { fg = p.bright_yellow })
hl("DiagnosticInfo", { fg = p.bright_blue })
hl("DiagnosticHint", { fg = p.bright_cyan })
hl("DiagnosticOk", { fg = p.bright_green })
hl("DiagnosticUnderlineError", { sp = p.bright_red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = p.bright_yellow, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = p.bright_blue, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = p.bright_cyan, undercurl = true })
hl("DiagnosticVirtualTextError", { fg = p.bright_red, bg = p.black })
hl("DiagnosticVirtualTextWarn", { fg = p.bright_yellow, bg = p.black })
hl("DiagnosticVirtualTextInfo", { fg = p.bright_blue, bg = p.black })
hl("DiagnosticVirtualTextHint", { fg = p.bright_cyan, bg = p.black })
hl("LspReferenceText", { bg = p.black })
hl("LspReferenceRead", { bg = p.black })
hl("LspReferenceWrite", { bg = p.black })
hl("LspInlayHint", { fg = p.bright_black, italic = true })
hl("LspSignatureActiveParameter", { fg = p.yellow, bold = true })
hl("DiagnosticSignError", { link = "DiagnosticError" })
hl("DiagnosticSignWarn", { link = "DiagnosticWarn" })
hl("DiagnosticSignInfo", { link = "DiagnosticInfo" })
hl("DiagnosticSignHint", { link = "DiagnosticHint" })
hl("DiagnosticSignOk", { link = "DiagnosticOk" })
hl("DiagnosticFloatingError", { link = "DiagnosticError" })
hl("DiagnosticFloatingWarn", { link = "DiagnosticWarn" })
hl("DiagnosticFloatingInfo", { link = "DiagnosticInfo" })
hl("DiagnosticFloatingHint", { link = "DiagnosticHint" })
hl("DiagnosticUnnecessary", { fg = p.bright_black })
hl("DiagnosticDeprecated", { fg = p.bright_black, strikethrough = true })

hl("@variable", { fg = p.fg })
hl("@variable.builtin", { fg = p.bright_red })
hl("@variable.parameter", { fg = p.peach })
hl("@variable.parameter.builtin", { fg = p.yellow, italic = true })
hl("@variable.member", { fg = p.teal })
hl("@constant", { fg = p.yellow })
hl("@constant.builtin", { fg = p.peach })
hl("@constant.macro", { fg = p.bright_red })
hl("@module", { fg = p.dim_yellow })
hl("@module.builtin", { fg = p.bright_red })
hl("@string", { fg = p.bright_green })
hl("@string.documentation", { fg = p.dim_yellow, italic = true })
hl("@string.escape", { fg = p.peach })
hl("@string.regexp", { fg = p.bright_magenta })
hl("@string.special", { fg = p.bright_cyan })
hl("@character", { fg = p.bright_green })
hl("@character.special", { fg = p.peach })
hl("@number", { fg = p.yellow })
hl("@number.float", { fg = p.peach })
hl("@boolean", { fg = p.peach })
hl("@function", { fg = p.bright_blue })
hl("@function.builtin", { fg = p.blue })
hl("@function.call", { fg = p.bright_blue })
hl("@function.macro", { fg = p.bright_red })
hl("@function.method", { fg = p.bright_blue })
hl("@function.method.call", { fg = p.bright_blue })
hl("@constructor", { fg = p.dim_yellow })
hl("@constructor.tsx", { fg = p.ice })
hl("@keyword", { fg = p.bright_magenta })
hl("@keyword.function", { fg = p.magenta })
hl("@keyword.return", { fg = p.bright_magenta })
hl("@keyword.operator", { fg = p.bright_cyan })
hl("@keyword.import", { fg = p.bright_blue })
hl("@keyword.coroutine", { fg = p.hot_pink })
hl("@keyword.conditional", { fg = p.bright_magenta })
hl("@keyword.repeat", { fg = p.bright_magenta })
hl("@keyword.exception", { fg = p.bright_red })
hl("@keyword.debug", { fg = p.bright_red })
hl("@keyword.directive", { fg = p.dim_yellow })
hl("@keyword.storage", { fg = p.dim_yellow })
hl("@operator", { fg = p.bright_cyan })
hl("@punctuation", { fg = p.bright_black })
hl("@punctuation.bracket", { fg = p.bright_black })
hl("@punctuation.delimiter", { fg = p.cyan })
hl("@punctuation.special", { fg = p.bright_cyan })
hl("@punctuation.special.markdown", { fg = p.peach })
hl("@type", { fg = p.bright_yellow })
hl("@type.builtin", { fg = p.dim_yellow })
hl("@type.definition", { fg = p.bright_yellow })
hl("@type.qualifier", { fg = p.bright_magenta })
hl("@property", { fg = p.teal })
hl("@attribute", { fg = p.dim_yellow })
hl("@label", { fg = p.bright_blue })
hl("@comment", { fg = p.bright_black, italic = true })
hl("@comment.todo", { fg = p.bright_yellow, bold = true })
hl("@comment.error", { fg = p.bright_red, bold = true })
hl("@comment.warning", { fg = p.yellow, bold = true })
hl("@comment.note", { fg = p.bright_cyan, bold = true })
hl("@comment.hint", { fg = p.ice, bold = true })
hl("@tag", { fg = p.bright_red })
hl("@tag.attribute", { fg = p.teal })
hl("@tag.delimiter", { fg = p.bright_black })
hl("@tag.tsx", { fg = p.bright_red })
hl("@tag.javascript", { fg = p.bright_red })
hl("@tag.delimiter.tsx", { fg = p.blue })
hl("@markup.heading", { fg = p.bright_yellow, bold = true })
hl("@markup.heading.1.markdown", { fg = p.bright_red, bold = true })
hl("@markup.heading.2.markdown", { fg = p.peach, bold = true })
hl("@markup.heading.3.markdown", { fg = p.bright_yellow, bold = true })
hl("@markup.heading.4.markdown", { fg = p.bright_green, bold = true })
hl("@markup.heading.5.markdown", { fg = p.bright_cyan, bold = true })
hl("@markup.heading.6.markdown", { fg = p.bright_blue, bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.underline", { underline = true })
hl("@markup.link", { fg = p.bright_blue, underline = true })
hl("@markup.link.label", { fg = p.peach })
hl("@markup.link.url", { fg = p.bright_cyan, underline = true })
hl("@markup.raw", { fg = p.bright_green })
hl("@markup.raw.markdown_inline", { fg = p.ice, bg = p.black })
hl("@markup.list", { fg = p.bright_cyan })
hl("@markup.list.checked", { fg = p.bright_green })
hl("@markup.list.unchecked", { fg = p.bright_blue })
hl("@markup.quote", { fg = p.bright_black, italic = true })
hl("@markup.math", { fg = p.ice })
hl("@diff.plus", { link = "DiffAdd" })
hl("@diff.minus", { link = "DiffDelete" })
hl("@diff.delta", { link = "DiffChange" })

hl("@lsp.type.class", { link = "@type" })
hl("@lsp.type.comment", { link = "@comment" })
hl("@lsp.type.decorator", { link = "@attribute" })
hl("@lsp.type.enum", { link = "@type" })
hl("@lsp.type.enumMember", { link = "@constant" })
hl("@lsp.type.event", { fg = p.peach })
hl("@lsp.type.function", { link = "@function" })
hl("@lsp.type.interface", { fg = p.ice })
hl("@lsp.type.keyword", { link = "@keyword" })
hl("@lsp.type.macro", { link = "Macro" })
hl("@lsp.type.method", { link = "@function.method" })
hl("@lsp.type.modifier", { link = "@keyword" })
hl("@lsp.type.namespace", { link = "@module" })
hl("@lsp.type.namespace.python", { link = "@variable" })
hl("@lsp.type.number", { link = "@number" })
hl("@lsp.type.operator", { link = "@operator" })
hl("@lsp.type.parameter", { link = "@variable.parameter" })
hl("@lsp.type.property", { link = "@property" })
hl("@lsp.type.regexp", { link = "@string.regexp" })
hl("@lsp.type.string", { link = "@string" })
hl("@lsp.type.struct", { link = "@type" })
hl("@lsp.type.type", { link = "@type" })
hl("@lsp.type.typeParameter", { fg = p.dim_yellow, italic = true })
hl("@lsp.type.variable", { link = "@variable" })
hl("@lsp.type.boolean", { link = "@boolean" })
hl("@lsp.type.builtinType", { link = "@type.builtin" })
hl("@lsp.type.escapeSequence", { link = "@string.escape" })
hl("@lsp.type.formatSpecifier", { fg = p.ice })
hl("@lsp.type.selfKeyword", { link = "@variable.builtin" })
hl("@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hl("@lsp.type.selfParameter", { link = "@variable.builtin" })
hl("@lsp.type.typeAlias", { link = "@type" })
hl("@lsp.type.unresolvedReference", { fg = p.hot_pink, sp = p.hot_pink, undercurl = true })
hl("@lsp.type.lifetime", { fg = p.ice, italic = true })
hl("@lsp.type.generic", { link = "@variable" })
hl("@lsp.type.deriveHelper", { link = "@attribute" })
hl("@lsp.type.const", { link = "Constant" })
hl("@lsp.type.punctuation", { link = "Delimiter" })
hl("@lsp.type.comparison", { link = "@operator" })
hl("@lsp.type.bitwise", { link = "@operator" })
hl("@lsp.type.magicFunction", { link = "@function.builtin" })
hl("@lsp.type.builtinConstant", { link = "@constant.builtin" })
hl("@lsp.type.decorator.rust", { fg = p.dim_yellow })
hl("@lsp.mod.deprecated", { fg = p.bright_black, strikethrough = true })
hl("@lsp.mod.readonly", { fg = p.yellow })
hl("@lsp.mod.typeHint", { link = "@type" })
hl("@lsp.typemod.variable.defaultLibrary", { fg = p.bright_red })
hl("@lsp.typemod.variable.static", { fg = p.yellow })
hl("@lsp.typemod.variable.readonly", { fg = p.yellow })
hl("@lsp.typemod.variable.global", { fg = p.peach })
hl("@lsp.typemod.variable.injected", { link = "@variable" })
hl("@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hl("@lsp.typemod.function.builtin", { link = "@function.builtin" })
hl("@lsp.typemod.function.readonly", { fg = p.bright_blue, bold = true })
hl("@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hl("@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hl("@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hl("@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hl("@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hl("@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hl("@lsp.typemod.keyword.injected", { link = "@keyword" })
hl("@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hl("@lsp.typemod.keyword.documentation", { fg = p.ice })
hl("@lsp.typemod.string.injected", { link = "@string" })
hl("@lsp.typemod.operator.injected", { link = "@operator" })
hl("@lsp.typemod.operator.controlFlow", { fg = p.hot_pink, bold = true })

hl("BlinkCmpKindField", { fg = p.teal })
hl("BlinkCmpKindProperty", { fg = p.teal })
hl("BlinkCmpKindVariable", { fg = p.bright_red })
hl("BlinkCmpKindFunction", { fg = p.bright_blue })
hl("BlinkCmpKindMethod", { fg = p.bright_blue })
hl("BlinkCmpKindClass", { fg = p.bright_yellow })
hl("BlinkCmpKindInterface", { fg = p.ice })
hl("BlinkCmpKindModule", { fg = p.dim_yellow })
hl("BlinkCmpKindKeyword", { fg = p.bright_magenta })
hl("BlinkCmpKindSnippet", { fg = p.bright_green })
hl("BlinkCmpKindText", { fg = p.bright_black })
hl("BlinkCmpKindConstant", { fg = p.yellow })
hl("BlinkCmpKindEnum", { fg = p.bright_yellow })
hl("BlinkCmpKindColor", { fg = p.hot_pink })

hl("GitSignsAdd", { fg = p.bright_green })
hl("GitSignsChange", { fg = p.bright_yellow })
hl("GitSignsDelete", { fg = p.bright_red })
hl("GitSignsAddLn", { bg = p.black })
hl("GitSignsChangeLn", { bg = p.black })
hl("GitSignsDeleteLn", { bg = p.black })

hl("FlashBackdrop", { fg = p.bright_black })
hl("FlashMatch", { fg = p.bg, bg = p.bright_blue })
hl("FlashCurrent", { fg = p.bg, bg = p.yellow })
hl("FlashLabel", { fg = p.bg, bg = p.bright_red, bold = true })

hl("SnacksNormal", { fg = p.fg, bg = p.bg })
hl("SnacksNormalNC", { fg = p.fg, bg = p.bg })
hl("SnacksBorder", { fg = p.bright_black, bg = p.bg })
hl("SnacksTitle", { fg = p.bright_yellow, bg = p.bg, bold = true })
hl("SnacksIndent", { fg = p.black })
hl("SnacksIndentScope", { fg = p.bright_black })
hl("SnacksDashboardHeader", { fg = p.bright_yellow })
hl("SnacksDashboardIcon", { fg = p.bright_blue })
hl("SnacksDashboardKey", { fg = p.yellow })
hl("SnacksDashboardDesc", { fg = p.bright_black })
hl("SnacksDashboardFooter", { fg = p.bright_black, italic = true })
hl("SnacksDashboardSpecial", { fg = p.bright_magenta })
hl("SnacksPickerBorder", { fg = p.bright_black, bg = p.bg })
hl("SnacksPickerTitle", { fg = p.bright_yellow, bg = p.bg })
hl("SnacksPickerMatch", { fg = p.yellow, bold = true })
hl("SnacksPickerDir", { fg = p.bright_blue })
hl("SnacksPickerFile", { fg = p.fg })
hl("SnacksPickerSelected", { fg = p.bright_cyan })
hl("SnacksNotifierInfo", { fg = p.bright_blue })
hl("SnacksNotifierWarn", { fg = p.bright_yellow })
hl("SnacksNotifierError", { fg = p.bright_red })

hl("BlinkCmpMenu", { fg = p.fg, bg = p.black })
hl("BlinkCmpMenuBorder", { fg = p.bright_black, bg = p.black })
hl("BlinkCmpMenuSelection", { fg = p.bg, bg = p.bright_blue })
hl("BlinkCmpDoc", { fg = p.fg, bg = p.black })
hl("BlinkCmpDocBorder", { fg = p.bright_black, bg = p.black })
hl("BlinkCmpGhostText", { fg = p.bright_black })
hl("BlinkCmpLabel", { fg = p.fg })
hl("BlinkCmpLabelMatch", { fg = p.yellow, bold = true })
hl("BlinkCmpKind", { fg = p.bright_magenta })

hl("WhichKey", { fg = p.yellow })
hl("WhichKeyGroup", { fg = p.bright_blue })
hl("WhichKeyDesc", { fg = p.fg })
hl("WhichKeySeparator", { fg = p.bright_black })
hl("WhichKeyFloat", { bg = p.black })
hl("WhichKeyBorder", { fg = p.bright_black, bg = p.black })
hl("NoiceCmdlinePopup", { fg = p.fg, bg = p.black })
hl("NoiceCmdlinePopupBorder", { fg = p.bright_black, bg = p.black })
hl("NoiceCmdlineIcon", { fg = p.bright_blue })
hl("LazyNormal", { fg = p.fg, bg = p.black })
hl("LazyButton", { fg = p.fg, bg = p.black })
hl("LazyButtonActive", { fg = p.bg, bg = p.bright_blue })
hl("LazyH1", { fg = p.bg, bg = p.bright_yellow, bold = true })
hl("MasonHeader", { fg = p.bg, bg = p.bright_yellow, bold = true })
hl("MasonHighlight", { fg = p.bright_blue })

hl("MiniIndentscopeSymbol", { fg = p.bright_black })
hl("MiniIconsAzure", { fg = p.bright_blue })
hl("MiniIconsBlue", { fg = p.bright_blue })
hl("MiniIconsCyan", { fg = p.bright_cyan })
hl("MiniIconsGreen", { fg = p.bright_green })
hl("MiniIconsOrange", { fg = p.yellow })
hl("MiniIconsPurple", { fg = p.bright_magenta })
hl("MiniIconsRed", { fg = p.bright_red })
hl("MiniIconsYellow", { fg = p.bright_yellow })
hl("MiniIconsGrey", { fg = p.bright_black })
hl("BufferLineFill", { bg = p.bg })
hl("BufferLineBufferSelected", { fg = p.fg, bg = p.bg, bold = true })
hl("BufferLineBufferVisible", { fg = p.bright_black, bg = p.bg })
hl("BufferLineBackground", { fg = p.bright_black, bg = p.bg })
hl("TroubleNormal", { fg = p.fg, bg = p.bg })
hl("TodoBgTODO", { fg = p.bg, bg = p.bright_yellow, bold = true })
hl("TodoFgTODO", { fg = p.bright_yellow })
hl("TodoBgFIX", { fg = p.bg, bg = p.bright_red, bold = true })
hl("TodoFgFIX", { fg = p.bright_red })
hl("TodoBgHACK", { fg = p.bg, bg = p.yellow, bold = true })
hl("TodoFgHACK", { fg = p.yellow })
hl("TodoBgNOTE", { fg = p.bg, bg = p.bright_cyan, bold = true })
hl("TodoFgNOTE", { fg = p.bright_cyan })

vim.g.terminal_color_0 = p.black
vim.g.terminal_color_1 = p.red
vim.g.terminal_color_2 = p.green
vim.g.terminal_color_3 = p.yellow
vim.g.terminal_color_4 = p.blue
vim.g.terminal_color_5 = p.magenta
vim.g.terminal_color_6 = p.cyan
vim.g.terminal_color_7 = p.white
vim.g.terminal_color_8 = p.bright_black
vim.g.terminal_color_9 = p.bright_red
vim.g.terminal_color_10 = p.bright_green
vim.g.terminal_color_11 = p.bright_yellow
vim.g.terminal_color_12 = p.bright_blue
vim.g.terminal_color_13 = p.bright_magenta
vim.g.terminal_color_14 = p.bright_cyan
vim.g.terminal_color_15 = p.bright_white
